# demonstrate Coverity on Polaris quality gate with getIssues
name: cop-getIssues
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    env:
      POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      POLARIS_PROJECT: ${{ github.event.repository.name }}
      POLARIS_ZIP: polaris_cli-linux64.zip
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Polaris Scan
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/$POLARIS_ZIP
        unzip -d $RUNNER_TEMP -jo $POLARIS_ZIP && rm -f $POLARIS_ZIP
        $RUNNER_TEMP/polaris --co project.name=$POLARIS_PROJECT analyze -w
    - name: Polaris Quality Gate
      run: |
        curl -fLOsS https://www.chuckaude.com/repo/getIssues && chmod +x getIssues
        ./getIssues --project $POLARIS_PROJECT --branch ${{ github.ref_name }} --severity high --spec checker,path --exit1-if-issues
